/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import org.fourthline.cling.model.meta.LocalService;
import upnp.LuminositeService;
import upnp.OrdreService;

/**
 *
 * @author telly
 */
public class Fenetre extends javax.swing.JFrame {
    private Etat etat;
    private LocalService<OrdreService> orderService;
    private LocalService<LuminositeService> luminositeService;
    
    private void init(){
        etat = Etat.Deverouille;
        bt_eclaircir.setEnabled(false);
        bt_activer.setEnabled(false);
        slider.setValue(lumiere1.getLuminosite());
    } 
    
    private void actualiser_etat(){
        if(etat == Etat.Verouille){
            deverouiller();
            activer_boutons();
        } else verouiller();
    }
    
    private void verouiller(){
        etat = Etat.Verouille;
        slider.setEnabled(false);
        bt_eclaircir.setEnabled(false);
        bt_noircir.setEnabled(false);
        bt_desactiver.setEnabled(false);
        bt_activer.setEnabled(true);
    }
    
    private void deverouiller(){
        etat = Etat.Deverouille;
        slider.setEnabled(true);
        bt_eclaircir.setEnabled(true);
        bt_noircir.setEnabled(true);
        bt_desactiver.setEnabled(true);
        bt_activer.setEnabled(false);
    }
    
    private void activer_boutons(){
        if(lumiere1.getLuminosite() == 100)
            bt_eclaircir.setEnabled(false);
        else bt_eclaircir.setEnabled(true);
        if(lumiere1.getLuminosite() == 0)
            bt_noircir.setEnabled(false);
        else bt_noircir.setEnabled(true);
    }
    /**
     * Creates new form Fenetre
     */
    public Fenetre() {
        initComponents();
        init();
    }

    public Fenetre( LocalService<OrdreService> order,
                    LocalService<LuminositeService> lumi){
        initComponents();
        init();
        this.orderService = order;
        this.luminositeService = lumi;
        
        this.orderService.getManager().getImplementation().getPropertyChangeSupport().addPropertyChangeListener(
                new PropertyChangeListener() {
                   @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if(evt.getPropertyName().equals("status")){
                            actualiser_etat();
                        }
            }
        }
        );
        
        this.luminositeService.getManager().getImplementation().getPropertyChangeSupport().addPropertyChangeListener(
                new PropertyChangeListener() {
                    @Override
                    public void propertyChange(PropertyChangeEvent pce) {
                        if(pce.getPropertyName().equals("valeur") && !(etat.equals(Etat.Verouille))){
                            lumiere1.setLuminosite(
                                Integer.parseInt((String) pce.getNewValue())
                            );
                            lumiere1.actualiser();
                            slider.setValue(lumiere1.getLuminosite());
                        }
                    }
        }
        );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lumiere1 = new display.Lumiere();
        bt_noircir = new javax.swing.JButton();
        bt_eclaircir = new javax.swing.JButton();
        slider = new javax.swing.JSlider();
        bt_activer = new javax.swing.JButton();
        bt_desactiver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout lumiere1Layout = new javax.swing.GroupLayout(lumiere1);
        lumiere1.setLayout(lumiere1Layout);
        lumiere1Layout.setHorizontalGroup(
            lumiere1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lumiere1Layout.setVerticalGroup(
            lumiere1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        bt_noircir.setText("Noircir");
        bt_noircir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_noircirActionPerformed(evt);
            }
        });

        bt_eclaircir.setText("Eclairir");
        bt_eclaircir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eclaircirActionPerformed(evt);
            }
        });

        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        bt_activer.setText("Activer");
        bt_activer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_activerActionPerformed(evt);
            }
        });

        bt_desactiver.setText("Desactiver");
        bt_desactiver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_desactiverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bt_eclaircir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_noircir)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_desactiver)
                            .addComponent(bt_activer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lumiere1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lumiere1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_activer)
                        .addGap(18, 18, 18)
                        .addComponent(bt_desactiver)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_noircir)
                    .addComponent(bt_eclaircir))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_noircirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_noircirActionPerformed
        // TODO add your handling code here:
        lumiere1.darker();
        slider.setValue(lumiere1.getLuminosite());
    }//GEN-LAST:event_bt_noircirActionPerformed

    private void bt_eclaircirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eclaircirActionPerformed
        // TODO add your handling code here:
        lumiere1.brighter();
        slider.setValue(lumiere1.getLuminosite());
    }//GEN-LAST:event_bt_eclaircirActionPerformed

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        int value = slider.getValue();
        lumiere1.setLuminosite(value);
        lumiere1.actualiser();
        activer_boutons();
    }//GEN-LAST:event_sliderStateChanged

    private void bt_activerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_activerActionPerformed
        // TODO add your handling code here:
        actualiser_etat();
    }//GEN-LAST:event_bt_activerActionPerformed

    private void bt_desactiverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_desactiverActionPerformed
        // TODO add your handling code here:
        actualiser_etat();
    }//GEN-LAST:event_bt_desactiverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_activer;
    private javax.swing.JButton bt_desactiver;
    private javax.swing.JButton bt_eclaircir;
    private javax.swing.JButton bt_noircir;
    private display.Lumiere lumiere1;
    private javax.swing.JSlider slider;
    // End of variables declaration//GEN-END:variables
}
